const baseUrl = "https://fight-tracker.vercel.app";

type MetadataParams = {
  title: string;
  description: string;
  keywords?: string[];
  path?: string;
};

const sharedMetadata = {
  keywords: [
    "MMA",
    "Mixed Martial Arts",
    "UFC",
    "Ultimate Fighting Championship",
    "PFL",
    "Professional Fighters League",
    "LFA",
    "Legacy Fighting Alliance",
    "ONE",
    "ONE Championship",
    "One Fighting Championship",
    "BKFC",
    "Bare Knuckle Fighting Championship",
    "ESPN",
    "ESPN MMA",
    "fight events",
    "upcoming fights",
    "upcoming fight events",
    "sports events",
    "fight tracker",
    "UFC rankings",
    "current UFC rankings",
    "rankings",
    "athletes",
    "UFC athletes",
    "fighters",
    "UFC fighters",
    "best fighters",
    "best UFC fighters",
    "top fighters",
    "top UFC fighters",
    "favorites",
    "favorite fighters",
    "your favorite fighters",
    "divisions",
    "champions",
    "weight classes",
    "UFC weight classes",
    "weight divisions",
    "UFC weight divisions",
    "UFC fight history",
    "fighter records",
    "past UFC events",
    "fight results",
    "UFC career",
    "fighter performance",
    "UFC matchups",
    "fight statistics",
    "UFC fight cards",
    "historical fights",
    "fighter journey",
    "UFC timeline",
    "fight analysis",
    "UFC archives",
    "fighter evolution",
    "fighter progression",
    "MMA news",
    "UFC news",
    "PFL news",
    "combat sports news",
    "latest MMA news",
    "breaking MMA news",
    "fight news",
    "live fight coverage",
    "MMA rumors",
    "UFC rumors",
    "PFL rumors",
    "MMA opinions",
    "UFC opinions",
    "PFL opinions",
    "MMA discussions",
    "UFC discussions",
    "PFL discussions",
    "fight announcements",
    "MMA updates",
    "UFC updates",
    "PFL updates",
    "fight reports",
    "MMA headlines",
    "sports news MMA",
    "fight world news",
    "MMA event coverage",
    "fighter interviews",
    "MMA press releases",
    "MMA press conference",
    "fighter reactions",
    "live MMA events",
    "fight results UFC",
    "expert fight analysis",
    "fight statistics UFC",
    "MMA controversies",
    "UFC predictions",
    "PFL predictions",
    "MMA rankings updates",
    "biggest UFC fights",
    "MMA breaking stories",
    "sports journalism MMA",
    "UFC betting odds",
    "fight industry news",
    "MMA media reports",
    "UFC weigh-in results",
    "PFL weigh-in results",
  ],
  openGraph: {
    type: "website",
    images: [`${baseUrl}/images/og-image.png`],
  },
};

export function createMetadata({
  title,
  description,
  keywords = [],
  path = "",
}: MetadataParams) {
  const allKeywords = [...sharedMetadata.keywords, ...keywords].join(", ");

  return {
    title: `${title} | Fight Tracker`,
    description,
    keywords: allKeywords,
    openGraph: {
      ...sharedMetadata.openGraph,
      title: `${title} | Fight Tracker`,
      description,
      url: `${baseUrl}${path}`,
    },
  };
}
